spring:
  application:
    name: trip97
  # DB Setting
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy
    url: jdbc:mysql://localhost:3306/trip97?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
  web:
    resources:
      static-locations: "file:///C:/trip97/hotPlace/upload/"
# Jwt Setting
jwt:
  secret-key: ${JWT_SECRET_KEY}

# OAuth Setting
oauth:
  naver:
    secret: ${OAUTH_NAVER_SECRET}
    client-id: HVfS8Bx6TTsiC8oIVVib
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

kauth:
  kakao:
    secret: ${KAUTH_KAKAO_SECRET}
    client-id: ${KAKAO_REST_API}
    url :
      auth : https://kauth.kakao.com
      api : https://kapi.kakao.com

# MyBatis Setting
mybatis:
  type-handlers-package: com.quietjun.oauthtest.model.typehandlers
  type-aliases-package: com.trip97.modules.*.model
  mapper-locations: mapper/*.xml

# file upload path : window
file:
  path: C:/trip97/hotPlace/upload/

# local domain
local:
  domain: http://localhost:8080